name: Publish-CI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: echo ${{github.ref}}
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: npm package, test and storybook generation
      run: |
        npm run package
        npm run test
        npm run storybook:build
    - uses: actions/upload-artifact@v2
      with:
        name: storybook-demo
        path: storybook-static/
      env:
        CI: true

  publish:

    runs-on: ubuntu-latest

    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Publish on artifactory
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: npm package, test and storybook generation to NPM Repository
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npm config set scope "@trystan2k"
          npm config list
          yarn
          yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://npm.pkg.github.com'
          scope: '@trystan2k'
      - name: npm package, test and storybook generation to Github package repository
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:

    runs-on: ubuntu-latest

    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Release new version
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

  deploy:

    runs-on: ubuntu-latest

    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: storybook-demo
          path: demo-public
      - name: Display structure of downloaded files
        run: ls -R

      - name: Deploy on Netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --prod --dir=demo-public
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
